Windows build compatibility -- Actions for Trelis 17.1 and Cubit 2020.2
svalinn/DAGMC-Trelis pull request #85
Opened 2021-02-24 19:30 UTC by bam241

This should not be reviewed before #84 gets merged. It builds on top of #84 and relies on some of those change.
This also relies on multiples PR to be merged on dependencies such as `MOAB`, `DAGMC` and `mncp2cad`

This includes:
- script to build Trelis plugin on Windows
- GitHub action to build the windows plugin for Trelis 17.1 and Cubit 2020.2

This is NOT a standalone PR, it is depending on:
- svalinn/mcnp2cad#74
- svalinn/dagmc#727
- [MOAB/moab#522](https://bitbucket.org/fathomteam/moab/pull-requests/522/building-moab-shared-lib-on-windows-using)

2021-02-24 19:31 UTC, bam241 commented on .github/workflows/windows.yml
> +          git clone https://bitbucket.org/bam241/moab -b windows_2
Need to be changed after MOAB PR get merged.

2021-02-24 19:31 UTC, bam241 commented on .github/workflows/windows.yml
> +          git clone https://github.com/bam241/dagmc -b windows
Need to be changed after `DAGMC` PR get merged.

2021-02-24 19:32 UTC, bam241 commented on .github/workflows/windows.yml
> +          git clone  https://github.com/bam241/mcnp2cad -b windows
Need to be changed after `mcnp2cad` PR gets merged.

2021-02-24 19:32 UTC, bam241 commented on .github/workflows/windows.yml
> +                -DUPDATE_SUBMODULES=OFF \
Need to be changed after `mcnp2cad` PR gets merged.

2021-08-25 11:32 UTC, gonuke commented
Do we use the `build_windows.sh` script anymore?

2021-08-25 11:57 UTC, Shimwell commented
Wow this will be a great addition. Super work BaM.

I notice it uses the ```run-on``` windows-2019 option. Wondering if it would also work as ```run-on``` ubuntu but use an windows-2019 ```image``` for the build then we could perhaps easily include other images like the windows-2022 image if needed

2021-08-25 12:02 UTC, bam241 commented
> Do we use the `build_windows.sh` script anymore?

we never had one for windows.

2021-08-25 12:16 UTC, gonuke commented
> > Do we use the `build_windows.sh` script anymore?
> 
> 
> 
> we never had one for windows.

But I don't see it being used anywhere because the GH action explicitly includes all the build instructions instead

2021-08-25 12:19 UTC, bam241 commented
> > > Do we use the `build_windows.sh` script anymore?
> > 
> > 
> > we never had one for windows.
> 
> But I don't see it being used anywhere because the GH action explicitly includes all the build instructions instead

sorry, I lost track of that file..

this is an artefact of previous work. that will need to be removed eventually...

2021-08-25 12:28 UTC, bam241 commented
> Wow this will be a great addition. Super work BaM.
> 
> I notice it uses the `run-on` windows-2019 option. Wondering if it would also work as `run-on` ubuntu but use an windows-2019 `image` for the build then we could perhaps easily include other images like the windows-2022 image if needed

yes this is something we should/could consider in the future. I would like to keep this PR simple, as a first support of windows.  I think we would need first to update that on the DAGMC CI.... to extend our windows capability. 
One should also check that multiple windows build would be required, maybe (if we are lucky) a single build would be compatible with multiple windows version.... (as for Mac OS)

2021-08-25 12:44 UTC, bam241 commented
current problem seems to be on core form side...
https://coreform.com/products/downloads/

don't see any download available on their website.... maybe their server crashed....

2021-08-25 15:56 UTC, shimwell commented
> current problem seems to be on core form side...
> https://coreform.com/products/downloads/
> 
> don't see any download available on their website.... maybe their server crashed....

I think it might be the cloud host https://downdetector.com/status/backblaze/

2021-08-26 10:51 UTC, gonuke requested changes
We need to choose best release actions to trigger a build

2021-08-26 10:51 UTC, gonuke commented on .github/workflows/windows.yml
> +      - created
I think we learned last week that `created` was not a good choice. It is possible to create a draft release, which then triggers this, but when you publish the release, it does not trigger again.


@Shimwell , did we pick a better one? Or maybe an additional one?

2021-08-26 10:56 UTC, shimwell commented on .github/workflows/windows.yml
> +      - created
I believe we preferred ```published```

2021-08-26 10:59 UTC, shimwell commented on .github/workflows/windows.yml
> +      - created
All the options are here https://docs.github.com/en/actions/reference/events-that-trigger-workflows#release

There is also a discussion here https://github.community/t/what-is-the-created-type-in-on-release/17184

2021-08-27 13:46 UTC, bam241 commented
@gonuke this looks good to go ? 
Anya additional comments/requests ?

2021-08-27 14:03 UTC, gonuke requested changes
Thanks @bam241 - exciting to see this getting close.  Two items, only one is blocking.

2021-08-27 14:03 UTC, gonuke commented on .github/workflows/windows.yml
> +          msiexec.exe /i HDF5-1.8.21-win64.msi /passive /norestart
question: does this mean that conda's HDF5 won't work? also the conda-forge version?  I wonder if we can document this somewhere so that if/when someone tries again, they know what the problem(s) were

2021-08-27 14:03 UTC, gonuke commented on .github/workflows/windows.yml
> +          tar -cvf svalinn_plugin_windows_${{ matrix.cubit }}.tar  bin
should we use `7z` to make a zip file instead of a tarball?

2021-08-30 17:09 UTC, bam241 commented
@gonuke it seems to be working, using hdf5 conda and 7x :)

2021-08-30 17:15 UTC, gonuke requested changes
Can we get the ZIP format?

2021-08-30 17:15 UTC, gonuke commented on .github/workflows/windows.yml
> +          7z a C:/Users/runneradmin/svalinn_plugin_windows_${{ matrix.cubit }}.7z  bin\
Can we make this with a `.zip` extension and ZIP format?

2021-08-30 17:20 UTC, gonuke commented on .github/workflows/windows.yml
> +          7z a C:/Users/runneradmin/svalinn_plugin_windows_${{ matrix.cubit }}.7z  bin\
P.S. Thanks for figuring the rest out, @bam241 !

2021-08-30 18:21 UTC, gonuke approved these changes
Excellent!!! Thanks @bam241

2021-08-30 18:21 UTC, merged