Removing Trelis mention
svalinn/DAGMC-Trelis pull request #98
Opened 2021-05-25 18:41 UTC by bam241

converting Trelis mention to Cubit.

This should probably come with a repo renaming

2021-05-25 18:55 UTC, bam241 commented
some mention are still present in `scripts` and `mcnp2cad`

the `scripts` one should done after #86 that take care of some of them.

a sperate PR is required for `mcnp2cad`

2021-05-26 22:37 UTC, gonuke commented on scripts/build_plugin_linux.sh
> +# $1 is the version of Cubit one are trying to compile against i.e. 17.1.0
```suggestion
# $1 is the version of Cubit one is trying to compile against i.e. 17.1.0
```

2021-05-26 22:38 UTC, gonuke requested changes
I made one comment outside of this review, but I think this looks OK.  I assume it's failing tests because the repo has not been renamed?

2021-05-26 22:54 UTC, bam241 commented
> I made one comment outside of this review, but I think this looks OK. I assume it's failing tests because the repo has not been renamed?

Yes:
```
/home/runner/work/Trelis-plugin/Trelis-plugin/scripts/unix_share_build.sh: line 199: cd: Cubit-plugin: No such file or directory
```

2021-05-28 09:52 UTC, gonuke commented
Should we announce a plan to rename the repo and then rename it before merging this?

2021-06-03 18:34 UTC, bam241 commented
yes I was thinking on using Thursday meeting for this

2021-06-03 20:20 UTC, pshriwise commented
This now has some conflicts after merging #97. I'd be happy to review it as soon as they are resolved.

2021-06-04 02:34 UTC, gonuke commented
We also need to stage this for the change in repo name

2021-06-04 14:39 UTC, bam241 commented
@pshriwise @gonuke this has been rebased.
let's discuss Thursday about the course of actions for this.

2021-06-08 13:29 UTC, pshriwise requested changes
Looking pretty good. Just a few suggestions comments from me. Thanks for keeping us up to date, @bam241.

2021-06-08 13:29 UTC, pshriwise commented on README.md
> +The plugin has been tested and is confirmed to work with various Cubit  versions 17.1 up to 2020.2.
```suggestion
The plugin has been tested and is confirmed to work with various Cubit versions 17.1 up to 2020.2. 
```

2021-06-08 13:29 UTC, pshriwise commented on README.md
> +This installs Cubit to `/opt/Coreform-Cubit-VERSION` or `/opt/Trelis-VERSION` for old version.
Do we still want the Trelis mention here?

2021-06-08 13:29 UTC, pshriwise commented on README.md
>  variable is empty**. This variable is not needed to build MOAB, DAGMC, or the
```suggestion
variable is empty**. 

```bash
unset LD_LIBRARY_PATH
```

This variable is not needed to build MOAB, DAGMC, or the
```

2021-06-08 13:29 UTC, pshriwise commented on README.md
>  `/usr/lib/x86_64-linux-gnu/hdf5/serial` directory, but it may be located
This is a ubuntu-specific location for hdf5. We may want to point that out.

2021-06-08 13:29 UTC, pshriwise commented on README.md
>  # Set the RPATH to be the current directory for the DAGMC libraries
Some explanation of these commands is warranted. Something like:

"The resulting shared library objects require an update to their `RPATH` (runtime path) attribute to ensure that the correct set of libraries is discovered when starting Cubit and loading the plugin library."

2021-06-08 13:29 UTC, pshriwise commented on README.md
> +This installs Cubit to `/opt/Coreform-Cubit-VERSION` or `/opt/Trelis-VERSION` for old version.
```suggestion
This installs Cubit to `/opt/Coreform-Cubit-VERSION` or `/opt/Trelis-VERSION` for older versions.
```

2021-06-08 13:29 UTC, pshriwise commented on README.md
> +For Cubit version older than 2021 one need to manually install the provided SDK
```suggestion
For Cubit versions older than 2021, one needs to manually install the provided SDK
```

2021-06-08 13:46 UTC, bam241 commented on README.md
> +This installs Cubit to `/opt/Coreform-Cubit-VERSION` or `/opt/Trelis-VERSION` for old version.
I keep it because they still mention Trelis 17.1 on the Coreform website, and we still actively support 17.1...

2021-06-17 19:26 UTC, bam241 commented
@gonuke @pshriwise this is ready for a last run of review or a merge !

2021-06-17 19:27 UTC, gonuke approved these changes

2021-06-17 19:38 UTC, bam241 commented on README.md
>  `/usr/lib/x86_64-linux-gnu/hdf5/serial` directory, but it may be located
we kinda do the line before, or do you mean something else ?

2021-06-17 20:52 UTC, pshriwise commented on README.md
>  `/usr/lib/x86_64-linux-gnu/hdf5/serial` directory, but it may be located
So we do. Must've missed that. My bad!

2021-06-17 20:53 UTC, pshriwise approved these changes
Looks great. Thanks @bam241!

2021-06-17 20:53 UTC, merged